  [[main]]
  name = "Hem"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Blog"
  weight = 200
  identifier = "posts"
  url = "/artiklar/"

  [[main]]
  name = "Om"
  weight = 400
  identifier = "about"
  url = "/om/"

  [[footer]]
  name = "Christian Karlsson"
  weight = 1
  identifier = "about"
  url = "/om/"