baseURL = 'karlssonxyz.netlify.app'
languageCode = 'en-us'
title = 'Christian Karlsson'
theme = 'minimal-theme'

[[menus.main]]
name = 'Hem'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"