baseURL = 'https://karlsson.xyz/'
languageCode = 'sv_SE'
defaultContentLanguage = "sv"
defaultContentLang = "sv"
title = 'Christian Karlsson'
theme = "anatole"
author = "Christian Karlsson"
description = ""
copyright = "2023-{{ YEAR }}"



[[params.socialIcons]]
icon = "fab fa-mastodon"
rel = "me"
title = "mastodon"
url = "https://social.karlsson.xyz/@christian"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://instagram.com/mrckarlsson"

[[params.socialIcons]]
icon = "fas fa-rss"
title = "rss"
url = ""

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:christian@karlsson.xyz"

[menu]

  [[menu.main]]
  name = "Hem"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Kategori"
  weight = 200
  identifier = "category"
  url = "/kategori/"

  [[menu.main]]
  name = "Följ"
  weight = 300
  identifier = "follow"
  url = "/folj/"