baseURL = 'https://karlsson.xyz/'
languageCode = 'sv_SE'
defaultContentLanguage = "sv"
defaultContentLang = "sv"
title = 'Christian Karlsson'
theme = "hugo-theme-fred"

[[menus.main]]
name = 'Hem'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Artiklar'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'Om'
pageRef = 'about'
weight = 40